/*
 * C1 capability graph — a JS-native transcription of
 * `docs/curriculum/blueprints/c1.json#/capabilities`, `#/skillFamilies` and
 * `#/assumedPriorLevelCapabilities` / `#/priorLevelReconciliation`. Every id,
 * prerequisite, evidence target and CEFR reference here must match that
 * file; `scripts/foundry/c1/check-c1-blueprint-fidelity.mjs` diffs the two
 * and fails the moment they drift.
 *
 * Field names deliberately mirror c1.json's OWN schema (not B2's, which uses
 * a different shape — `scope` vs `priority`, `patterns` vs
 * `languageInfrastructure`, `evidence: {...}` object vs a flat
 * `independentEvidence` number) so the fidelity check can walk both
 * structures identically, the same discipline `b2Capabilities.js` documents
 * for its own blueprint.
 *
 * Nothing in this file is imported by any runtime module yet (mirrors B2's
 * and A1's own blueprint-before-content discipline). Wiring this into
 * `curriculum/levelMaps.js`, `engine/scaffolding.js`, or any shared evaluator
 * dispatch is out of `LC-CONT-C1`'s write scope — see
 * `docs/curriculum/implementation/c1/core-engine-handoff.md`.
 */

export const C1_PREREQUISITE_LEVEL = 'b2'

/*
 * Real B2 capability ids C1 depends on, reconciled against
 * `docs/curriculum/blueprints/b2.json` by LC-AUD-001/LC-FND-002 (see
 * c1.json#/priorLevelReconciliation). Not a C1-owned id — never redefine one
 * of these here.
 *
 * HONEST NOTE: `weigh_implications_of_a_position`'s own prerequisites array
 * in c1.json still reads the pre-reconciliation id `b2_weigh_advantages_and_disadvantages`
 * (underscore, not b2.'s dot notation) with `crossLevelPrerequisite: "assumed"`,
 * even though c1.md's section 0/3 prose describes this row as already
 * resolved to `b2.weigh_advantages_and_disadvantages` ("already resolves —
 * B2 landed with this exact id"). c1.json (the machine-checked data file) and
 * c1.md (its own human-readable index) disagree with each other on this one
 * row. `docs/curriculum/blueprints/**` is not in this task's write scope, so
 * this file transcribes c1.json's literal field values below (the fidelity
 * check compares against c1.json) rather than silently "fixing" the id to
 * match the prose — recorded here and in
 * `docs/curriculum/implementation/c1/README.md` for a human/LC-AUD-001-style
 * follow-up, the same honesty discipline B2 used for its own
 * reuseMatrix/b2Reuse mismatch.
 */
export const C1_B2_PREREQUISITES = [
  'b2.develop_and_defend_opinion',
  'b2.adjust_register_to_context',
  'b2.summarize_for_someone_else',
  'b2.infer_implied_meaning',
  'b2.negotiate_a_resolution',
  'b2.sustain_a_multi_topic_conversation',
  'b2_weigh_advantages_and_disadvantages', // literal c1.json id — see honest note above
]

export const C1_SKILL_FAMILIES = [
  { id: 'abstract_argument', label: 'Taking a position', canDos: ['develop_a_structured_argument', 'qualify_a_claim_precisely', 'concede_a_counterpoint_gracefully', 'weigh_implications_of_a_position'] },
  { id: 'register_and_diplomacy', label: 'Getting the tone right', canDos: ['adapt_register_to_audience', 'hedge_and_mitigate_a_statement', 'disagree_diplomatically', 'repair_a_register_slip'] },
  { id: 'synthesis_and_mediation', label: 'Making sense of it for someone else', canDos: ['summarize_a_complex_message_for_a_new_audience', 'synthesize_two_conflicting_viewpoints', 'reformulate_for_a_different_audience', 'paraphrase_to_avoid_repetition'] },
  { id: 'nuance_and_implication', label: 'Reading between the lines', canDos: ['infer_implied_meaning_in_unfamiliar_context', 'express_degrees_of_certainty', 'hold_a_nuanced_stance', 'recognize_understatement_or_irony'] },
  { id: 'extended_structured_discourse', label: 'Saying more, in order', canDos: ['produce_an_extended_structured_explanation', 'use_cohesive_devices_across_a_turn', 'self_correct_without_losing_the_thread', 'open_and_close_an_extended_turn'] },
  { id: 'negotiation_and_complexity', label: 'Working it out', canDos: ['negotiate_a_mutually_acceptable_outcome', 'clarify_an_ambiguous_instruction_precisely', 'propose_and_defend_an_alternative', 'handle_an_unexpected_complication'] },
  { id: 'sustained_interaction', label: 'Staying in it', canDos: ['sustain_a_conversation_across_topic_shifts', 'refer_back_to_earlier_discourse', 'shift_register_within_one_conversation', 'close_a_complex_interaction_with_a_summary'] },
]

/*
 * One entry per `c1.json#/capabilities` record, same field names as the
 * blueprint. 21 required, 7 should, 0 optional (c1.md section 3).
 */
export const C1_CAPABILITIES = [
  {
    id: 'develop_a_structured_argument', family: 'abstract_argument',
    canDo: 'build a position with a claim, supporting reasons and an example, organized so a listener can follow it',
    cefrRefs: ['Sustained Monologue: Putting a Case', 'Overall Oral Production'],
    priority: 'required',
    prerequisites: ['b2.develop_and_defend_opinion'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F5, high confidence)',
    languageInfrastructure: ['emphatic_cleft_pattern', 'hedging_modal_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 10, receptiveVocabulary: 12,
    firstContext: 'abstract_argument',
    reuseContexts: ['extended_structured_discourse', 'negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['a topic never used in teaching, argued with the same structure'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'qualify_a_claim_precisely', family: 'abstract_argument',
    canDo: "narrow or broaden a claim with precise hedging language instead of an absolute statement",
    cefrRefs: ['Coherence and Cohesion'],
    priority: 'required',
    prerequisites: ['develop_a_structured_argument'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['hedging_modal_pattern', 'hedging_adverbial_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 8,
    firstContext: 'abstract_argument',
    reuseContexts: ['register_and_diplomacy', 'nuance_and_implication', 'negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['qualifying a claim on a topic never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'reused unprompted in negotiation_and_complexity after two intervening arcs',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'concede_a_counterpoint_gracefully', family: 'abstract_argument',
    canDo: 'acknowledge a valid opposing point without abandoning or contradicting their own position',
    cefrRefs: ['Formal Discussion and Meetings'],
    priority: 'required',
    prerequisites: ['develop_a_structured_argument', 'qualify_a_claim_precisely'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['concessive_clause_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 8,
    firstContext: 'abstract_argument',
    reuseContexts: ['register_and_diplomacy', 'synthesis_and_mediation', 'nuance_and_implication', 'sustained_interaction'],
    transferContexts: ['conceding a counterpoint on a topic never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'weigh_implications_of_a_position', family: 'abstract_argument',
    canDo: 'reason through a likely consequence of a stance and state it',
    cefrRefs: ['Sustained Monologue: Putting a Case'],
    priority: 'should',
    prerequisites: ['concede_a_counterpoint_gracefully', 'b2_weigh_advantages_and_disadvantages'],
    crossLevelPrerequisite: 'assumed',
    languageInfrastructure: ['hedging_modal_pattern', 'conditional_alternative_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'abstract_argument',
    reuseContexts: ['negotiation_and_complexity'],
    transferContexts: ['reasoning through a consequence on a topic never used in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'adapt_register_to_audience', family: 'register_and_diplomacy',
    canDo: 'choose vocabulary/structure/directness appropriate to who they are speaking to',
    cefrRefs: ['Sociolinguistic Appropriateness'],
    priority: 'required',
    prerequisites: ['b2.adjust_register_to_context'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F5, high confidence)',
    languageInfrastructure: ['register_pair_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 12, receptiveVocabulary: 14,
    firstContext: 'register_and_diplomacy',
    reuseContexts: ['synthesis_and_mediation', 'extended_structured_discourse', 'sustained_interaction'],
    transferContexts: ['adapting register for a relationship never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'reused unprompted in extended_structured_discourse and sustained_interaction',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'hedge_and_mitigate_a_statement', family: 'register_and_diplomacy',
    canDo: 'soften a face-threatening statement with appropriate hedging devices',
    cefrRefs: ['Sociolinguistic Appropriateness', 'Goal-oriented Co-operation'],
    priority: 'required',
    prerequisites: ['adapt_register_to_audience', 'qualify_a_claim_precisely'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['mitigation_device_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 10, receptiveVocabulary: 10,
    firstContext: 'register_and_diplomacy',
    reuseContexts: ['negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['mitigating a statement in a relationship never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'disagree_diplomatically', family: 'register_and_diplomacy',
    canDo: 'express disagreement while preserving the relationship and leaving room to respond',
    cefrRefs: ['Goal-oriented Co-operation'],
    priority: 'required',
    prerequisites: ['hedge_and_mitigate_a_statement', 'concede_a_counterpoint_gracefully'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['mitigation_device_pattern', 'concessive_clause_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 8,
    firstContext: 'register_and_diplomacy',
    reuseContexts: ['negotiation_and_complexity'],
    transferContexts: ['diplomatic disagreement in a genuinely new relationship context'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'repair_a_register_slip', family: 'register_and_diplomacy',
    canDo: 'notice and self-correct when their own phrasing was too blunt/casual/formal',
    cefrRefs: ['Sociolinguistic Appropriateness'],
    priority: 'should',
    prerequisites: ['adapt_register_to_audience', 'hedge_and_mitigate_a_statement'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['register_pair_pattern', 'self_repair_discourse_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'register_and_diplomacy',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['repairing a register slip in a situation never used in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'summarize_a_complex_message_for_a_new_audience', family: 'synthesis_and_mediation',
    canDo: 'reduce a longer message to its essential point(s) for someone who needs the gist',
    cefrRefs: ['Processing Text / Mediating a Text'],
    priority: 'required',
    prerequisites: ['b2.summarize_for_someone_else'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F5, high confidence)',
    languageInfrastructure: ['cohesive_connector_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 10, receptiveVocabulary: 16,
    firstContext: 'synthesis_and_mediation',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['summarizing a source never seen in teaching for an audience type not used before'],
    independentEvidence: 3,
    delayedRetrieval: "reused in sustained_interaction's closing summary",
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'synthesize_two_conflicting_viewpoints', family: 'synthesis_and_mediation',
    canDo: 'state, in one coherent account, what two sources agree and disagree on',
    cefrRefs: ['Processing Text', 'Reading for Information and Argument'],
    priority: 'required',
    prerequisites: ['summarize_a_complex_message_for_a_new_audience', 'concede_a_counterpoint_gracefully'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['evaluative_reporting_pattern', 'cohesive_connector_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 12,
    firstContext: 'synthesis_and_mediation',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['synthesizing two sources never seen in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'reformulate_for_a_different_audience', family: 'synthesis_and_mediation',
    canDo: 'restate the same content in simpler or more technical language depending on who is listening',
    cefrRefs: ['Processing Text / Mediating a Text'],
    priority: 'required',
    prerequisites: ['summarize_a_complex_message_for_a_new_audience', 'adapt_register_to_audience'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['register_pair_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 10,
    firstContext: 'synthesis_and_mediation',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['reformulating content never seen in teaching for a new audience type'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'paraphrase_to_avoid_repetition', family: 'synthesis_and_mediation',
    canDo: 'say the same thing again, differently, when the first phrasing should not be repeated verbatim',
    cefrRefs: ['Coherence and Cohesion'],
    priority: 'should',
    prerequisites: ['reformulate_for_a_different_audience'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['self_repair_discourse_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'synthesis_and_mediation',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['paraphrasing content never seen in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'infer_implied_meaning_in_unfamiliar_context', family: 'nuance_and_implication',
    canDo: 'correctly infer what a speaker means when it is not stated directly',
    cefrRefs: ['Conversation', 'Reading for Information and Argument'],
    priority: 'required',
    prerequisites: ['b2.infer_implied_meaning'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F2/F5, high confidence). This id was renamed from infer_implied_meaning (colliding with B2\'s should-scope receptive capability of the same id, LC-AUD-001 F2): it escalates B2\'s should-scope receptive infer_implied_meaning to a required C1 productive/interpretive capability, and is now a real cross-level prerequisite rather than a re-declaration.',
    languageInfrastructure: ['evaluative_reporting_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 4, receptiveVocabulary: 14,
    firstContext: 'nuance_and_implication',
    reuseContexts: ['negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['inferring meaning from a hint pattern not used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'reused unprompted in negotiation_and_complexity and sustained_interaction',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'express_degrees_of_certainty', family: 'nuance_and_implication',
    canDo: 'mark how confident they are in a claim rather than presenting everything as equally certain',
    cefrRefs: ['Coherence and Cohesion'],
    priority: 'required',
    prerequisites: ['qualify_a_claim_precisely'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['certainty_marking_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 8, receptiveVocabulary: 8,
    firstContext: 'nuance_and_implication',
    reuseContexts: ['negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['marking certainty on a claim never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'hold_a_nuanced_stance', family: 'nuance_and_implication',
    canDo: 'agree with part of an idea while disagreeing with another part, without flattening it',
    cefrRefs: ['Formal Discussion and Meetings'],
    priority: 'required',
    prerequisites: ['express_degrees_of_certainty', 'concede_a_counterpoint_gracefully'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['emphatic_cleft_pattern', 'concessive_clause_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'nuance_and_implication',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['holding a nuanced stance on a topic never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'recognize_understatement_or_irony', family: 'nuance_and_implication',
    canDo: 'correctly interpret an ironic or deliberately understated remark rather than taking it literally',
    cefrRefs: ['Conversation'],
    priority: 'should',
    prerequisites: ['infer_implied_meaning_in_unfamiliar_context'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['evaluative_reporting_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 2, receptiveVocabulary: 10,
    firstContext: 'nuance_and_implication',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['recognizing understatement/irony in a pattern not used in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'produce_an_extended_structured_explanation', family: 'extended_structured_discourse',
    canDo: 'deliver an organized, several-sentence account of a situation/plan/process with a beginning, development and close',
    cefrRefs: ['Sustained Monologue', 'Coherence and Cohesion'],
    priority: 'required',
    prerequisites: ['develop_a_structured_argument'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['cohesive_connector_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 10, receptiveVocabulary: 10,
    firstContext: 'extended_structured_discourse',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['producing an extended structured explanation about a topic never rehearsed'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'use_cohesive_devices_across_a_turn', family: 'extended_structured_discourse',
    canDo: 'link sentences within an extended turn with appropriate connectors instead of a flat list',
    cefrRefs: ['Coherence and Cohesion'],
    priority: 'required',
    prerequisites: ['produce_an_extended_structured_explanation'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['cohesive_connector_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 10, receptiveVocabulary: 10,
    firstContext: 'extended_structured_discourse',
    reuseContexts: ['synthesis_and_mediation', 'negotiation_and_complexity', 'sustained_interaction'],
    transferContexts: ['using cohesive devices in a turn about a topic never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: "reused unprompted in sustained_interaction's closing summary",
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'self_correct_without_losing_the_thread', family: 'extended_structured_discourse',
    canDo: 'notice and repair their own error mid-turn while keeping the explanation coherent',
    cefrRefs: ['Sustained Monologue'],
    priority: 'required',
    prerequisites: ['use_cohesive_devices_across_a_turn'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['self_repair_discourse_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'extended_structured_discourse',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['self-correcting mid-turn on a topic never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'open_and_close_an_extended_turn', family: 'extended_structured_discourse',
    canDo: 'signal clearly that an extended turn is starting and ending',
    cefrRefs: ['Sustained Monologue'],
    priority: 'should',
    prerequisites: ['produce_an_extended_structured_explanation'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['cohesive_connector_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 4, receptiveVocabulary: 4,
    firstContext: 'extended_structured_discourse',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['framing an extended turn in a context never used in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'negotiate_a_mutually_acceptable_outcome', family: 'negotiation_and_complexity',
    canDo: "propose, adjust and settle on an outcome that addresses both sides' stated constraints",
    cefrRefs: ['Goal-oriented Co-operation'],
    priority: 'required',
    prerequisites: ['b2.negotiate_a_resolution', 'disagree_diplomatically'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F5, high confidence)',
    languageInfrastructure: ['conditional_alternative_pattern', 'mitigation_device_pattern'],
    semanticNeeds: ['topic', 'negotiated_item'],
    productiveVocabulary: 12, receptiveVocabulary: 12,
    firstContext: 'negotiation_and_complexity',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['negotiating an outcome for constraints never seen in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'clarify_an_ambiguous_instruction_precisely', family: 'negotiation_and_complexity',
    canDo: 'ask a targeted follow-up question that resolves genuine ambiguity',
    cefrRefs: ['Conversation'],
    priority: 'required',
    prerequisites: ['infer_implied_meaning_in_unfamiliar_context'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['certainty_marking_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'negotiation_and_complexity',
    reuseContexts: ['sustained_interaction'],
    transferContexts: ['clarifying an ambiguous instruction never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'reused unprompted in sustained_interaction',
    graduationRelevance: 'required', evaluation: 'hybrid',
    intentReuse: 'repair_request with a new repairKind subtype: ask_for_precision',
  },
  {
    id: 'propose_and_defend_an_alternative', family: 'negotiation_and_complexity',
    canDo: 'when the original plan will not work, offer a different one and justify why it meets the same need',
    cefrRefs: ['Goal-oriented Co-operation'],
    priority: 'required',
    prerequisites: ['negotiate_a_mutually_acceptable_outcome', 'develop_a_structured_argument'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['conditional_alternative_pattern'],
    semanticNeeds: ['topic', 'negotiated_item'],
    productiveVocabulary: 8, receptiveVocabulary: 8,
    firstContext: 'negotiation_and_complexity',
    reuseContexts: [],
    transferContexts: ['proposing and defending an alternative in a situation never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'one unprompted independent use after at least one intervening arc',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'handle_an_unexpected_complication', family: 'negotiation_and_complexity',
    canDo: 'respond coherently when a new fact changes the situation mid-conversation',
    cefrRefs: ['Goal-oriented Co-operation'],
    priority: 'should',
    prerequisites: ['propose_and_defend_an_alternative', 'clarify_an_ambiguous_instruction_precisely'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['conditional_alternative_pattern', 'self_repair_discourse_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 4, receptiveVocabulary: 4,
    firstContext: 'negotiation_and_complexity',
    reuseContexts: [],
    transferContexts: ['handling an unexpected complication never used in teaching'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
  {
    id: 'sustain_a_conversation_across_topic_shifts', family: 'sustained_interaction',
    canDo: 'follow and productively participate as a conversation moves between two or three related topics',
    cefrRefs: ['Conversation'],
    priority: 'required',
    prerequisites: ['b2.sustain_a_multi_topic_conversation', 'infer_implied_meaning_in_unfamiliar_context'],
    crossLevelPrerequisite: 'resolved (LC-AUD-001 F5, medium confidence — b2.handle_a_topic_shift_gracefully is a plausible alternate/secondary prerequisite per the audit)',
    languageInfrastructure: ['cohesive_connector_pattern', 'anaphoric_reference_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 8,
    firstContext: 'sustained_interaction',
    reuseContexts: [],
    transferContexts: ['sustaining a conversation across topic shifts never used in teaching'],
    independentEvidence: 3,
    delayedRetrieval: 'this arc is itself the delayed-retrieval arc for earlier capabilities',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'refer_back_to_earlier_discourse', family: 'sustained_interaction',
    canDo: 'accurately reference something said earlier in the same conversation without restating it in full',
    cefrRefs: ['Coherence and Cohesion'],
    priority: 'required',
    prerequisites: ['sustain_a_conversation_across_topic_shifts'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['anaphoric_reference_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 4, receptiveVocabulary: 4,
    firstContext: 'sustained_interaction',
    reuseContexts: [],
    transferContexts: ['referring back to earlier discourse in a conversation shape never rehearsed'],
    independentEvidence: 3,
    delayedRetrieval: 'this arc is itself the delayed-retrieval arc for earlier capabilities',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'shift_register_within_one_conversation', family: 'sustained_interaction',
    canDo: 'adjust tone/formality mid-conversation when the situation itself shifts',
    cefrRefs: ['Sociolinguistic Appropriateness'],
    priority: 'required',
    prerequisites: ['sustain_a_conversation_across_topic_shifts', 'adapt_register_to_audience'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['register_pair_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 6, receptiveVocabulary: 6,
    firstContext: 'sustained_interaction',
    reuseContexts: [],
    transferContexts: ['shifting register within a conversation shape never rehearsed'],
    independentEvidence: 3,
    delayedRetrieval: 'this arc is itself the delayed-retrieval arc for earlier capabilities',
    graduationRelevance: 'required', evaluation: 'hybrid',
  },
  {
    id: 'close_a_complex_interaction_with_a_summary', family: 'sustained_interaction',
    canDo: 'end a longer conversation by briefly summarizing what was agreed/concluded',
    cefrRefs: ['Coherence and Cohesion', 'Conversation'],
    priority: 'should',
    prerequisites: ['refer_back_to_earlier_discourse', 'produce_an_extended_structured_explanation'],
    crossLevelPrerequisite: 'none',
    languageInfrastructure: ['cohesive_connector_pattern', 'anaphoric_reference_pattern'],
    semanticNeeds: ['topic'],
    productiveVocabulary: 4, receptiveVocabulary: 4,
    firstContext: 'sustained_interaction',
    reuseContexts: [],
    transferContexts: ['closing a complex interaction with a summary never rehearsed'],
    independentEvidence: 2,
    delayedRetrieval: 'none mandatory (should priority)',
    graduationRelevance: 'not_required_for_graduation', evaluation: 'hybrid',
  },
]

export const getC1Capability = (id) => C1_CAPABILITIES.find((c) => c.id === id) || null

export const C1_REQUIRED_CAPABILITY_IDS = C1_CAPABILITIES.filter((c) => c.priority === 'required').map((c) => c.id)
export const C1_SHOULD_CAPABILITY_IDS = C1_CAPABILITIES.filter((c) => c.priority === 'should').map((c) => c.id)

/*
 * `<LEVEL>_CAN_DO_INTENT`, the exact shape `curriculum/levelMaps.js` asks a
 * new level's own map file to export. Registering it into
 * `LEVEL_CAN_DO_INTENT_MAPS` is out of this task's write scope, so this
 * export exists here as the ready-to-register payload — see
 * `docs/curriculum/implementation/c1/core-engine-handoff.md`.
 *
 * One capability -> one intent, per c1.json#/evaluationIntents, EXCEPT
 * clarify_an_ambiguous_instruction_precisely, which reuses the existing
 * repair_request intent family with a new repairKind subtype
 * (ask_for_precision) rather than minting clarify_ambiguity as a standalone
 * intent id — matching the blueprint's own `intentReuse` field exactly (same
 * convention A1 uses for ask_meaning extending repair_request).
 */
export const C1_CAN_DO_INTENT = {
  develop_a_structured_argument: 'state_structured_argument',
  weigh_implications_of_a_position: 'state_structured_argument',
  qualify_a_claim_precisely: 'qualify_claim',
  express_degrees_of_certainty: 'qualify_claim',
  concede_a_counterpoint_gracefully: 'concede_point',
  hold_a_nuanced_stance: 'concede_point',
  adapt_register_to_audience: 'adapt_register',
  shift_register_within_one_conversation: 'adapt_register',
  repair_a_register_slip: 'adapt_register',
  hedge_and_mitigate_a_statement: 'hedge_statement',
  disagree_diplomatically: 'hedge_statement',
  summarize_a_complex_message_for_a_new_audience: 'summarize_message',
  reformulate_for_a_different_audience: 'summarize_message',
  paraphrase_to_avoid_repetition: 'summarize_message',
  synthesize_two_conflicting_viewpoints: 'synthesize_viewpoints',
  infer_implied_meaning_in_unfamiliar_context: 'infer_meaning',
  recognize_understatement_or_irony: 'infer_meaning',
  produce_an_extended_structured_explanation: 'extended_explanation',
  use_cohesive_devices_across_a_turn: 'extended_explanation',
  self_correct_without_losing_the_thread: 'extended_explanation',
  open_and_close_an_extended_turn: 'extended_explanation',
  negotiate_a_mutually_acceptable_outcome: 'negotiate_outcome',
  propose_and_defend_an_alternative: 'negotiate_outcome',
  handle_an_unexpected_complication: 'negotiate_outcome',
  clarify_an_ambiguous_instruction_precisely: 'repair_request', // subtype: ask_for_precision — see intentReuse above
  sustain_a_conversation_across_topic_shifts: 'track_discourse',
  refer_back_to_earlier_discourse: 'track_discourse',
  close_a_complex_interaction_with_a_summary: 'track_discourse',
}

export const C1_NEW_INTENT_COUNT = 12 // c1.json#/evaluationIntents.length (excludes the reused repair_request subtype)
