/*
 * C1 vocabulary — new lexical items beyond the 12 pattern groups themselves
 * (`c1Patterns.js` tracks every pattern as its own Garden-trackable unit,
 * same rule B2/A1 already use — this file is the REMAINING budget).
 *
 * HONEST RECONCILIATION NOTE: `c1.json#/capabilities[].productiveVocabulary`/
 * `receptiveVocabulary` are declared PER CAPABILITY and sum to 200
 * productive / 236 receptive across the level — well above the level-wide
 * `languageInfrastructure.vocabularyBudget.productiveItemsEstimate` ("90-110")
 * / `receptiveItemsEstimate` ("160-200"). The blueprint's own note says
 * these are "budget ceilings for LC-CONT-C1, not a pre-committed catalogue...
 * exact counts are finalized during LC-CONT-C1 against the actual authored
 * episodes" — i.e. this task has the authority to reconcile the mismatch,
 * which reads as the per-capability figures counting vocabulary a
 * capability's own evidence path EXERCISES (including items shared with
 * other capabilities in the same arc's hedging/certainty/register pool),
 * not vocabulary exclusively new to that capability alone. This file
 * authors real items totaling within the level-wide 90-110/160-200 range
 * (100 productive / 181 receptive), allocated per arc in rough proportion
 * to each arc's own capabilities' declared per-capability sums (see
 * `docs/curriculum/implementation/c1/README.md` for the exact allocation
 * table) — the same honest-reconciliation discipline B2 used for its own
 * reuseMatrix/b2Reuse mismatch, not a silent pick of one number.
 *
 * `glossKey` is a placeholder i18n key, not a translation — this task's
 * write scope does not include `i18n/**`.
 * `scripts/foundry/c1/list-c1-i18n-keys.mjs` mechanically generates the
 * exact manifest `LC-INT-001` needs to populate them.
 */

const item = (id, arc, kind, form, tiedCanDo, extra = {}) => ({
  id, arc, kind, form, tiedCanDo, glossKey: `c1Vocab_${id}`, ...extra,
})

export const C1_VOCABULARY = [
  // --- abstract_argument (target 16 productive / 26 receptive) ---
  item('what_really_matters_is', 'abstract_argument', 'productive', 'what really matters is', 'develop_a_structured_argument'),
  item('the_case_for_x_is', 'abstract_argument', 'productive', 'the case for X is', 'develop_a_structured_argument'),
  item('take_for_example', 'abstract_argument', 'productive', 'take, for example', 'develop_a_structured_argument'),
  item('to_illustrate', 'abstract_argument', 'productive', 'to illustrate', 'develop_a_structured_argument'),
  item('might_well', 'abstract_argument', 'productive', 'might well', 'qualify_a_claim_precisely'),
  item('is_unlikely_to', 'abstract_argument', 'productive', 'is unlikely to', 'qualify_a_claim_precisely'),
  item('to_some_extent', 'abstract_argument', 'productive', 'to some extent', 'qualify_a_claim_precisely'),
  item('by_and_large', 'abstract_argument', 'productive', 'by and large', 'qualify_a_claim_precisely'),
  item('not_necessarily', 'abstract_argument', 'productive', 'not necessarily', 'qualify_a_claim_precisely'),
  item('i_take_your_point_that', 'abstract_argument', 'productive', 'I take your point that', 'concede_a_counterpoint_gracefully'),
  item('while_its_true_that', 'abstract_argument', 'productive', "while it's true that", 'concede_a_counterpoint_gracefully'),
  item('that_said', 'abstract_argument', 'productive', 'that said', 'concede_a_counterpoint_gracefully'),
  item('fair_enough_but', 'abstract_argument', 'productive', 'fair enough, but', 'concede_a_counterpoint_gracefully'),
  item('it_would_likely_mean_that', 'abstract_argument', 'productive', 'it would likely mean that', 'weigh_implications_of_a_position'),
  item('the_knock_on_effect_would_be', 'abstract_argument', 'productive', 'the knock-on effect would be', 'weigh_implications_of_a_position'),
  item('to_play_devils_advocate', 'abstract_argument', 'productive', "to play devil's advocate", 'develop_a_structured_argument'),
  item('a_compelling_case', 'abstract_argument', 'receptive', 'a compelling case', 'develop_a_structured_argument'),
  item('an_absolutist_claim', 'abstract_argument', 'receptive', 'an absolutist claim', 'develop_a_structured_argument'),
  item('to_substantiate', 'abstract_argument', 'receptive', 'to substantiate', 'develop_a_structured_argument'),
  item('a_measured_position', 'abstract_argument', 'receptive', 'a measured position', 'develop_a_structured_argument'),
  item('to_overstate', 'abstract_argument', 'receptive', 'to overstate', 'qualify_a_claim_precisely'),
  item('a_sweeping_statement', 'abstract_argument', 'receptive', 'a sweeping statement', 'qualify_a_claim_precisely'),
  item('a_caveat', 'abstract_argument', 'receptive', 'a caveat', 'qualify_a_claim_precisely'),
  item('to_narrow_a_claim', 'abstract_argument', 'receptive', 'to narrow a claim', 'qualify_a_claim_precisely'),
  item('a_fair_concession', 'abstract_argument', 'receptive', 'a fair concession', 'concede_a_counterpoint_gracefully'),
  item('to_stand_ones_ground', 'abstract_argument', 'receptive', "to stand one's ground", 'concede_a_counterpoint_gracefully'),
  item('a_counterpoint', 'abstract_argument', 'receptive', 'a counterpoint', 'concede_a_counterpoint_gracefully'),
  item('in_good_faith', 'abstract_argument', 'receptive', 'in good faith', 'concede_a_counterpoint_gracefully'),
  item('a_likely_consequence', 'abstract_argument', 'receptive', 'a likely consequence', 'weigh_implications_of_a_position'),
  item('a_downstream_effect', 'abstract_argument', 'receptive', 'a downstream effect', 'weigh_implications_of_a_position'),
  item('to_reason_through', 'abstract_argument', 'receptive', 'to reason through (something)', 'weigh_implications_of_a_position'),
  item('an_ethical_dilemma', 'abstract_argument', 'receptive', 'an ethical dilemma', 'develop_a_structured_argument'),
  item('a_shared_local_resource', 'abstract_argument', 'receptive', 'a shared local resource', 'develop_a_structured_argument'),
  item('good_faith_pushback', 'abstract_argument', 'receptive', 'good-faith pushback', 'concede_a_counterpoint_gracefully'),
  item('screen_time', 'abstract_argument', 'receptive', 'screen time', 'develop_a_structured_argument'),
  item('a_pushy_argument', 'abstract_argument', 'receptive', 'a pushy argument', 'develop_a_structured_argument'),
  item('to_qualify_a_statement', 'abstract_argument', 'receptive', 'to qualify a statement', 'qualify_a_claim_precisely'),
  item('a_precise_hedge', 'abstract_argument', 'receptive', 'a precise hedge', 'qualify_a_claim_precisely'),
  item('a_likely_side_effect', 'abstract_argument', 'receptive', 'a likely side effect', 'weigh_implications_of_a_position'),
  item('to_weigh_a_position', 'abstract_argument', 'receptive', 'to weigh a position', 'weigh_implications_of_a_position'),
  item('a_work_life_balance_debate', 'abstract_argument', 'receptive', 'a work-life balance debate', 'develop_a_structured_argument'),
  item('a_reasoned_objection', 'abstract_argument', 'receptive', 'a reasoned objection', 'concede_a_counterpoint_gracefully'),

  // --- register_and_diplomacy (target 18 productive / 29 receptive) ---
  item('would_it_be_possible_to_c1', 'register_and_diplomacy', 'productive', 'would it be possible to', 'adapt_register_to_audience'),
  item('i_was_wondering_if_you_could_c1', 'register_and_diplomacy', 'productive', 'I was wondering if you could', 'adapt_register_to_audience'),
  item('would_you_mind_if', 'register_and_diplomacy', 'productive', 'would you mind if', 'adapt_register_to_audience'),
  item('could_you_possibly', 'register_and_diplomacy', 'productive', 'could you possibly', 'adapt_register_to_audience'),
  item('can_you', 'register_and_diplomacy', 'productive', 'can you', 'adapt_register_to_audience'),
  item('lets', 'register_and_diplomacy', 'productive', "let's", 'adapt_register_to_audience'),
  item('i_dont_want_to_overstate_this_but', 'register_and_diplomacy', 'productive', "I don't want to overstate this, but", 'hedge_and_mitigate_a_statement'),
  item('it_might_be_worth_considering', 'register_and_diplomacy', 'productive', 'it might be worth considering', 'hedge_and_mitigate_a_statement'),
  item('i_wonder_if', 'register_and_diplomacy', 'productive', 'I wonder if', 'hedge_and_mitigate_a_statement'),
  item('just_a_thought_but', 'register_and_diplomacy', 'productive', 'just a thought, but', 'hedge_and_mitigate_a_statement'),
  item('i_see_it_a_bit_differently', 'register_and_diplomacy', 'productive', 'I see it a bit differently', 'disagree_diplomatically'),
  item('id_push_back_on_that_slightly', 'register_and_diplomacy', 'productive', "I'd push back on that slightly", 'disagree_diplomatically'),
  item('im_not_sure_i_agree_because', 'register_and_diplomacy', 'productive', "I'm not sure I agree, because", 'disagree_diplomatically'),
  item('what_i_meant_to_say_was', 'register_and_diplomacy', 'productive', 'what I meant to say was', 'repair_a_register_slip'),
  item('let_me_rephrase_that', 'register_and_diplomacy', 'productive', 'let me rephrase that', 'repair_a_register_slip'),
  item('that_came_out_wrong', 'register_and_diplomacy', 'productive', 'that came out wrong', 'repair_a_register_slip'),
  item('sorry_that_sounded_blunter_than_i_meant', 'register_and_diplomacy', 'productive', 'sorry, that sounded blunter than I meant', 'repair_a_register_slip'),
  item('with_all_due_respect_c1', 'register_and_diplomacy', 'productive', 'with all due respect', 'adapt_register_to_audience'),
  item('face_threatening', 'register_and_diplomacy', 'receptive', 'face-threatening', 'hedge_and_mitigate_a_statement'),
  item('a_diplomatic_reply', 'register_and_diplomacy', 'receptive', 'a diplomatic reply', 'adapt_register_to_audience'),
  item('condescending_c1', 'register_and_diplomacy', 'receptive', 'condescending', 'adapt_register_to_audience'),
  item('overly_formal', 'register_and_diplomacy', 'receptive', 'overly formal', 'adapt_register_to_audience'),
  item('blunt_c1', 'register_and_diplomacy', 'receptive', 'blunt', 'adapt_register_to_audience'),
  item('a_register_mismatch', 'register_and_diplomacy', 'receptive', 'a register mismatch', 'adapt_register_to_audience'),
  item('to_soften_a_request', 'register_and_diplomacy', 'receptive', 'to soften a request', 'hedge_and_mitigate_a_statement'),
  item('a_mitigating_phrase', 'register_and_diplomacy', 'receptive', 'a mitigating phrase', 'hedge_and_mitigate_a_statement'),
  item('to_preserve_the_relationship', 'register_and_diplomacy', 'receptive', 'to preserve the relationship', 'disagree_diplomatically'),
  item('to_leave_room_to_respond', 'register_and_diplomacy', 'receptive', 'to leave room to respond', 'disagree_diplomatically'),
  item('a_tactful_disagreement', 'register_and_diplomacy', 'receptive', 'a tactful disagreement', 'disagree_diplomatically'),
  item('an_abrasive_tone', 'register_and_diplomacy', 'receptive', 'an abrasive tone', 'disagree_diplomatically'),
  item('to_notice_a_slip', 'register_and_diplomacy', 'receptive', "to notice a slip", 'repair_a_register_slip'),
  item('self_correcting', 'register_and_diplomacy', 'receptive', 'self-correcting', 'repair_a_register_slip'),
  item('to_walk_something_back', 'register_and_diplomacy', 'receptive', 'to walk something back', 'repair_a_register_slip'),
  item('declining_an_invitation_gracefully', 'register_and_diplomacy', 'receptive', 'declining an invitation gracefully', 'adapt_register_to_audience'),
  item('a_shared_living_disagreement', 'register_and_diplomacy', 'receptive', 'a shared-living disagreement', 'disagree_diplomatically'),
  item('difficult_feedback', 'register_and_diplomacy', 'receptive', 'difficult feedback', 'hedge_and_mitigate_a_statement'),
  item('an_unfamiliar_relationship', 'register_and_diplomacy', 'receptive', 'an unfamiliar relationship', 'adapt_register_to_audience'),
  item('a_relationship_sensitive_situation', 'register_and_diplomacy', 'receptive', 'a relationship-sensitive situation', 'adapt_register_to_audience'),
  item('to_read_the_room_c1', 'register_and_diplomacy', 'receptive', 'to read the room', 'adapt_register_to_audience'),
  item('a_gentle_pushback', 'register_and_diplomacy', 'receptive', 'a gentle pushback', 'disagree_diplomatically'),
  item('an_unintended_slight', 'register_and_diplomacy', 'receptive', 'an unintended slight', 'repair_a_register_slip'),
  item('to_take_the_edge_off', 'register_and_diplomacy', 'receptive', 'to take the edge off', 'hedge_and_mitigate_a_statement'),
  item('a_delicate_exchange', 'register_and_diplomacy', 'receptive', 'a delicate exchange', 'adapt_register_to_audience'),
  item('to_land_badly', 'register_and_diplomacy', 'receptive', 'to land badly', 'repair_a_register_slip'),
  item('a_genuine_apology', 'register_and_diplomacy', 'receptive', 'a genuine apology', 'repair_a_register_slip'),
  item('to_hold_ones_tone', 'register_and_diplomacy', 'receptive', "to hold one's tone", 'disagree_diplomatically'),
  item('a_junior_colleague', 'register_and_diplomacy', 'receptive', 'a junior colleague', 'adapt_register_to_audience'),
  item('a_senior_colleague', 'register_and_diplomacy', 'receptive', 'a senior colleague', 'adapt_register_to_audience'),

  // --- synthesis_and_mediation (target 16 productive / 34 receptive) ---
  item('the_essential_point_is', 'synthesis_and_mediation', 'productive', 'the essential point is', 'summarize_a_complex_message_for_a_new_audience'),
  item('boiled_down', 'synthesis_and_mediation', 'productive', 'boiled down, ...', 'summarize_a_complex_message_for_a_new_audience'),
  item('to_cut_a_long_story_short_c1', 'synthesis_and_mediation', 'productive', 'to cut a long story short', 'summarize_a_complex_message_for_a_new_audience'),
  item('both_sources_agree_that', 'synthesis_and_mediation', 'productive', 'both sources agree that', 'synthesize_two_conflicting_viewpoints'),
  item('where_they_differ_is', 'synthesis_and_mediation', 'productive', 'where they differ is', 'synthesize_two_conflicting_viewpoints'),
  item('on_the_other_hand_c1', 'synthesis_and_mediation', 'productive', 'on the other hand', 'synthesize_two_conflicting_viewpoints'),
  item('to_put_it_more_simply', 'synthesis_and_mediation', 'productive', 'to put it more simply', 'reformulate_for_a_different_audience'),
  item('in_more_technical_terms', 'synthesis_and_mediation', 'productive', 'in more technical terms', 'reformulate_for_a_different_audience'),
  item('for_someone_who_hasnt_seen_this_before', 'synthesis_and_mediation', 'productive', "for someone who hasn't seen this before", 'reformulate_for_a_different_audience'),
  item('to_put_it_another_way_c1', 'synthesis_and_mediation', 'productive', 'to put it another way', 'paraphrase_to_avoid_repetition'),
  item('or_rather', 'synthesis_and_mediation', 'productive', 'or rather', 'paraphrase_to_avoid_repetition'),
  item('in_other_words_c1', 'synthesis_and_mediation', 'productive', 'in other words', 'summarize_a_complex_message_for_a_new_audience'),
  item('the_gist_is', 'synthesis_and_mediation', 'productive', 'the gist is', 'summarize_a_complex_message_for_a_new_audience'),
  item('they_seemed_to_suggest_that', 'synthesis_and_mediation', 'productive', 'they seemed to suggest that', 'synthesize_two_conflicting_viewpoints'),
  item('she_implied_that', 'synthesis_and_mediation', 'productive', 'she implied that', 'synthesize_two_conflicting_viewpoints'),
  item('put_simply', 'synthesis_and_mediation', 'productive', 'put simply', 'reformulate_for_a_different_audience'),
  item('to_condense_c1', 'synthesis_and_mediation', 'receptive', 'to condense', 'summarize_a_complex_message_for_a_new_audience'),
  item('to_relay_accurately', 'synthesis_and_mediation', 'receptive', 'to relay accurately', 'summarize_a_complex_message_for_a_new_audience'),
  item('the_essential_gist', 'synthesis_and_mediation', 'receptive', 'the essential gist', 'summarize_a_complex_message_for_a_new_audience'),
  item('an_unnecessary_detail', 'synthesis_and_mediation', 'receptive', 'an unnecessary detail', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_source_text', 'synthesis_and_mediation', 'receptive', 'a source text', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_workplace_email_thread', 'synthesis_and_mediation', 'receptive', 'a workplace email thread', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_neighborhood_dispute', 'synthesis_and_mediation', 'receptive', 'a neighborhood dispute', 'synthesize_two_conflicting_viewpoints'),
  item('conflicting_instructions', 'synthesis_and_mediation', 'receptive', 'conflicting instructions', 'synthesize_two_conflicting_viewpoints'),
  item('to_reconcile_two_accounts', 'synthesis_and_mediation', 'receptive', 'to reconcile two accounts', 'synthesize_two_conflicting_viewpoints'),
  item('a_differing_account', 'synthesis_and_mediation', 'receptive', 'a differing account', 'synthesize_two_conflicting_viewpoints'),
  item('a_coherent_account', 'synthesis_and_mediation', 'receptive', 'a coherent account', 'synthesize_two_conflicting_viewpoints'),
  item('to_simplify_for_a_newcomer', 'synthesis_and_mediation', 'receptive', 'to simplify for a newcomer', 'reformulate_for_a_different_audience'),
  item('a_technical_audience', 'synthesis_and_mediation', 'receptive', 'a technical audience', 'reformulate_for_a_different_audience'),
  item('a_lay_audience', 'synthesis_and_mediation', 'receptive', 'a lay audience', 'reformulate_for_a_different_audience'),
  item('to_recast', 'synthesis_and_mediation', 'receptive', 'to recast (a statement)', 'reformulate_for_a_different_audience'),
  item('a_verbatim_copy', 'synthesis_and_mediation', 'receptive', 'a verbatim copy', 'paraphrase_to_avoid_repetition'),
  item('to_avoid_repeating_oneself', 'synthesis_and_mediation', 'receptive', 'to avoid repeating oneself', 'paraphrase_to_avoid_repetition'),
  item('a_rewording', 'synthesis_and_mediation', 'receptive', 'a rewording', 'paraphrase_to_avoid_repetition'),
  item('to_mediate_a_message', 'synthesis_and_mediation', 'receptive', 'to mediate a message', 'summarize_a_complex_message_for_a_new_audience'),
  item('the_grain_of_the_summary', 'synthesis_and_mediation', 'receptive', 'the right grain (of detail)', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_film_critique', 'synthesis_and_mediation', 'receptive', 'a film critique', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_travel_account', 'synthesis_and_mediation', 'receptive', 'a travel account', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_game_review', 'synthesis_and_mediation', 'receptive', 'a review of a game', 'summarize_a_complex_message_for_a_new_audience'),
  item('to_misrepresent_a_source', 'synthesis_and_mediation', 'receptive', 'to misrepresent a source', 'synthesize_two_conflicting_viewpoints'),
  item('a_valid_synthesis', 'synthesis_and_mediation', 'receptive', 'a valid synthesis', 'synthesize_two_conflicting_viewpoints'),
  item('a_biased_account', 'synthesis_and_mediation', 'receptive', 'a biased account', 'synthesize_two_conflicting_viewpoints'),
  item('a_neutral_account', 'synthesis_and_mediation', 'receptive', 'a neutral account', 'synthesize_two_conflicting_viewpoints'),
  item('a_key_takeaway_c1', 'synthesis_and_mediation', 'receptive', 'a key takeaway', 'summarize_a_complex_message_for_a_new_audience'),
  item('to_convey_accurately', 'synthesis_and_mediation', 'receptive', 'to convey accurately', 'reformulate_for_a_different_audience'),
  item('an_essential_point', 'synthesis_and_mediation', 'receptive', 'an essential point', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_relay_of_a_message', 'synthesis_and_mediation', 'receptive', 'a relay of a message', 'summarize_a_complex_message_for_a_new_audience'),
  item('an_original_source', 'synthesis_and_mediation', 'receptive', 'an original source', 'paraphrase_to_avoid_repetition'),
  item('to_state_the_gist', 'synthesis_and_mediation', 'receptive', 'to state the gist', 'summarize_a_complex_message_for_a_new_audience'),
  item('a_comprehension_phase', 'synthesis_and_mediation', 'receptive', 'a comprehension phase', 'summarize_a_complex_message_for_a_new_audience'),

  // --- nuance_and_implication (target 10 productive / 29 receptive) ---
  item('im_fairly_sure_that', 'nuance_and_implication', 'productive', "I'm fairly sure that", 'express_degrees_of_certainty'),
  item('its_not_clear_whether', 'nuance_and_implication', 'productive', "it's not clear whether", 'express_degrees_of_certainty'),
  item('theres_a_good_chance_that_c1', 'nuance_and_implication', 'productive', "there's a good chance that", 'express_degrees_of_certainty'),
  item('im_fairly_confident_that', 'nuance_and_implication', 'productive', "I'm fairly confident that", 'express_degrees_of_certainty'),
  item('what_they_probably_mean_is', 'nuance_and_implication', 'productive', 'what they probably mean is', 'infer_implied_meaning_in_unfamiliar_context'),
  item('reading_between_the_lines_c1', 'nuance_and_implication', 'productive', 'reading between the lines', 'infer_implied_meaning_in_unfamiliar_context'),
  item('i_have_a_feeling_theyre_actually_saying', 'nuance_and_implication', 'productive', "I have a feeling they're actually saying", 'infer_implied_meaning_in_unfamiliar_context'),
  item('i_can_see_your_point_but_i_still_think', 'nuance_and_implication', 'productive', 'I can see your point, but I still think', 'hold_a_nuanced_stance'),
  item('its_not_that_simple', 'nuance_and_implication', 'productive', "it's not that simple", 'hold_a_nuanced_stance'),
  item('i_dont_think_they_really_mean_that', 'nuance_and_implication', 'productive', "I don't think they really mean that", 'recognize_understatement_or_irony'),
  item('a_hint_c1', 'nuance_and_implication', 'receptive', 'a hint', 'infer_implied_meaning_in_unfamiliar_context'),
  item('an_undertone_c1', 'nuance_and_implication', 'receptive', 'an undertone', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_polite_non_committal_reply', 'nuance_and_implication', 'receptive', 'a polite non-committal reply', 'infer_implied_meaning_in_unfamiliar_context'),
  item('to_be_evasive', 'nuance_and_implication', 'receptive', 'to be evasive', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_veiled_reference', 'nuance_and_implication', 'receptive', 'a veiled reference', 'infer_implied_meaning_in_unfamiliar_context'),
  item('to_dodge_a_question', 'nuance_and_implication', 'receptive', 'to dodge a question', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_calibrated_guess', 'nuance_and_implication', 'receptive', 'a calibrated guess', 'express_degrees_of_certainty'),
  item('to_flatten_a_claim', 'nuance_and_implication', 'receptive', 'to flatten a claim', 'express_degrees_of_certainty'),
  item('an_honest_degree_of_certainty', 'nuance_and_implication', 'receptive', 'an honest degree of certainty', 'express_degrees_of_certainty'),
  item('to_hedge_ones_bets', 'nuance_and_implication', 'receptive', "to hedge one's bets", 'express_degrees_of_certainty'),
  item('a_nuanced_stance', 'nuance_and_implication', 'receptive', 'a nuanced stance', 'hold_a_nuanced_stance'),
  item('to_agree_in_part', 'nuance_and_implication', 'receptive', 'to agree in part', 'hold_a_nuanced_stance'),
  item('a_mixed_verdict', 'nuance_and_implication', 'receptive', 'a mixed verdict', 'hold_a_nuanced_stance'),
  item('an_understatement_c1', 'nuance_and_implication', 'receptive', 'an understatement', 'recognize_understatement_or_irony'),
  item('a_self_deprecating_remark', 'nuance_and_implication', 'receptive', 'a self-deprecating remark', 'recognize_understatement_or_irony'),
  item('deliberately_ironic', 'nuance_and_implication', 'receptive', 'deliberately ironic', 'recognize_understatement_or_irony'),
  item('to_take_something_literally', 'nuance_and_implication', 'receptive', 'to take something literally', 'recognize_understatement_or_irony'),
  item('a_diplomatic_non_answer', 'nuance_and_implication', 'receptive', 'a diplomatic non-answer', 'infer_implied_meaning_in_unfamiliar_context'),
  item('to_read_someones_tone', 'nuance_and_implication', 'receptive', "to read someone's tone", 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_backhanded_compliment_c1', 'nuance_and_implication', 'receptive', 'a backhanded compliment', 'recognize_understatement_or_irony'),
  item('loaded_language_c1', 'nuance_and_implication', 'receptive', 'loaded language', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_euphemism_c1', 'nuance_and_implication', 'receptive', 'a euphemism', 'infer_implied_meaning_in_unfamiliar_context'),
  item('passive_aggressive_c1', 'nuance_and_implication', 'receptive', 'passive-aggressive', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_diplomatic_colleague', 'nuance_and_implication', 'receptive', 'a diplomatic colleague', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_vague_friend', 'nuance_and_implication', 'receptive', 'a friend being vague', 'infer_implied_meaning_in_unfamiliar_context'),
  item('a_plan_going_wrong', 'nuance_and_implication', 'receptive', 'a plan going wrong', 'recognize_understatement_or_irony'),
  item('a_calibrated_claim', 'nuance_and_implication', 'receptive', 'a calibrated claim', 'express_degrees_of_certainty'),
  item('to_flatten_everything_to_yes_or_no', 'nuance_and_implication', 'receptive', 'to flatten everything to yes or no', 'express_degrees_of_certainty'),
  item('an_honest_reading', 'nuance_and_implication', 'receptive', 'an honest reading (of a situation)', 'hold_a_nuanced_stance'),

  // --- extended_structured_discourse (target 15 productive / 23 receptive) ---
  item('however_c1', 'extended_structured_discourse', 'productive', 'however', 'use_cohesive_devices_across_a_turn'),
  item('having_said_that_c1', 'extended_structured_discourse', 'productive', 'having said that', 'use_cohesive_devices_across_a_turn'),
  item('on_top_of_that', 'extended_structured_discourse', 'productive', 'on top of that', 'use_cohesive_devices_across_a_turn'),
  item('in_this_respect', 'extended_structured_discourse', 'productive', 'in this respect', 'use_cohesive_devices_across_a_turn'),
  item('as_a_result_c1', 'extended_structured_discourse', 'productive', 'as a result', 'use_cohesive_devices_across_a_turn'),
  item('so_to_start', 'extended_structured_discourse', 'productive', 'so, to start', 'open_and_close_an_extended_turn'),
  item('to_wrap_up', 'extended_structured_discourse', 'productive', 'to wrap up', 'open_and_close_an_extended_turn'),
  item('thats_the_situation_in_a_nutshell', 'extended_structured_discourse', 'productive', "that's the situation, in a nutshell", 'open_and_close_an_extended_turn'),
  item('what_i_mean_is_c1', 'extended_structured_discourse', 'productive', 'what I mean is', 'self_correct_without_losing_the_thread'),
  item('or_rather_c1', 'extended_structured_discourse', 'productive', 'or rather', 'self_correct_without_losing_the_thread'),
  item('let_me_put_that_differently', 'extended_structured_discourse', 'productive', 'let me put that differently', 'self_correct_without_losing_the_thread'),
  item('to_go_back_to_what_i_was_saying', 'extended_structured_discourse', 'productive', 'to go back to what I was saying', 'self_correct_without_losing_the_thread'),
  item('so_basically_what_happened_is', 'extended_structured_discourse', 'productive', 'so, basically, what happened is', 'produce_an_extended_structured_explanation'),
  item('the_first_thing_to_say_is', 'extended_structured_discourse', 'productive', 'the first thing to say is', 'produce_an_extended_structured_explanation'),
  item('as_a_result_of_that', 'extended_structured_discourse', 'productive', 'as a result of that', 'produce_an_extended_structured_explanation'),
  item('a_sustained_monologue', 'extended_structured_discourse', 'receptive', 'a sustained monologue', 'produce_an_extended_structured_explanation'),
  item('a_flat_list_of_sentences', 'extended_structured_discourse', 'receptive', 'a flat list (of sentences)', 'use_cohesive_devices_across_a_turn'),
  item('a_cohesive_turn', 'extended_structured_discourse', 'receptive', 'a cohesive turn', 'use_cohesive_devices_across_a_turn'),
  item('to_lose_the_thread', 'extended_structured_discourse', 'receptive', 'to lose the thread', 'self_correct_without_losing_the_thread'),
  item('to_recover_the_thread', 'extended_structured_discourse', 'receptive', 'to recover the thread', 'self_correct_without_losing_the_thread'),
  item('a_mid_turn_error', 'extended_structured_discourse', 'receptive', 'a mid-turn error', 'self_correct_without_losing_the_thread'),
  item('a_scheduling_mix_up', 'extended_structured_discourse', 'receptive', 'a scheduling mix-up', 'produce_an_extended_structured_explanation'),
  item('a_process_at_work', 'extended_structured_discourse', 'receptive', 'a process at work', 'produce_an_extended_structured_explanation'),
  item('a_beginning_a_development_and_a_close', 'extended_structured_discourse', 'receptive', 'a beginning, a development and a close', 'produce_an_extended_structured_explanation'),
  item('to_frame_an_extended_turn', 'extended_structured_discourse', 'receptive', 'to frame an extended turn', 'open_and_close_an_extended_turn'),
  item('to_signal_a_close', 'extended_structured_discourse', 'receptive', 'to signal a close', 'open_and_close_an_extended_turn'),
  item('an_organized_account', 'extended_structured_discourse', 'receptive', 'an organized account', 'produce_an_extended_structured_explanation'),
  item('a_connecting_device', 'extended_structured_discourse', 'receptive', 'a connecting device', 'use_cohesive_devices_across_a_turn'),
  item('a_contradictory_turn', 'extended_structured_discourse', 'receptive', 'a contradictory turn', 'use_cohesive_devices_across_a_turn'),
  item('off_topic_drift', 'extended_structured_discourse', 'receptive', 'off-topic drift', 'use_cohesive_devices_across_a_turn'),
  item('a_dangling_self_correction', 'extended_structured_discourse', 'receptive', 'a dangling self-correction', 'self_correct_without_losing_the_thread'),
  item('to_recount_how_a_plan_changed', 'extended_structured_discourse', 'receptive', 'to recount how a plan changed', 'produce_an_extended_structured_explanation'),
  item('a_linked_sentence', 'extended_structured_discourse', 'receptive', 'a linked sentence', 'use_cohesive_devices_across_a_turn'),
  item('an_extended_turn', 'extended_structured_discourse', 'receptive', 'an extended turn', 'open_and_close_an_extended_turn'),
  item('a_several_sentence_account', 'extended_structured_discourse', 'receptive', 'a several-sentence account', 'produce_an_extended_structured_explanation'),
  item('to_deliver_an_account', 'extended_structured_discourse', 'receptive', 'to deliver an account', 'produce_an_extended_structured_explanation'),
  item('a_genuine_repair', 'extended_structured_discourse', 'receptive', 'a genuine repair', 'self_correct_without_losing_the_thread'),
  item('a_signalled_change_of_subject', 'extended_structured_discourse', 'receptive', 'a signalled change of subject', 'use_cohesive_devices_across_a_turn'),

  // --- negotiation_and_complexity (target 15 productive / 23 receptive) ---
  item('what_if_we_c1', 'negotiation_and_complexity', 'productive', 'what if we', 'negotiate_a_mutually_acceptable_outcome'),
  item('would_you_be_willing_to_c1', 'negotiation_and_complexity', 'productive', 'would you be willing to', 'negotiate_a_mutually_acceptable_outcome'),
  item('lets_find_a_middle_ground', 'negotiation_and_complexity', 'productive', "let's find a middle ground", 'negotiate_a_mutually_acceptable_outcome'),
  item('that_way_neither_of_us_loses_out', 'negotiation_and_complexity', 'productive', "that way neither of us loses out", 'negotiate_a_mutually_acceptable_outcome'),
  item('when_you_say_x_do_you_mean', 'negotiation_and_complexity', 'productive', 'when you say X, do you mean', 'clarify_an_ambiguous_instruction_precisely'),
  item('could_you_be_more_specific_about', 'negotiation_and_complexity', 'productive', 'could you be more specific about', 'clarify_an_ambiguous_instruction_precisely'),
  item('just_to_make_sure_i_understood', 'negotiation_and_complexity', 'productive', 'just to make sure I understood', 'clarify_an_ambiguous_instruction_precisely'),
  item('if_that_doesnt_work_how_about', 'negotiation_and_complexity', 'productive', "if that doesn't work, how about", 'propose_and_defend_an_alternative'),
  item('an_alternative_that_would_still', 'negotiation_and_complexity', 'productive', 'an alternative that would still (meet the need)', 'propose_and_defend_an_alternative'),
  item('that_way_we_still_get', 'negotiation_and_complexity', 'productive', 'that way we still get', 'propose_and_defend_an_alternative'),
  item('given_this_new_information', 'negotiation_and_complexity', 'productive', 'given this new information', 'handle_an_unexpected_complication'),
  item('that_changes_things_slightly', 'negotiation_and_complexity', 'productive', 'that changes things slightly', 'handle_an_unexpected_complication'),
  item('lets_adjust_for_that', 'negotiation_and_complexity', 'productive', "let's adjust for that", 'handle_an_unexpected_complication'),
  item('as_a_gesture_of_goodwill_c1', 'negotiation_and_complexity', 'productive', 'as a gesture of goodwill', 'negotiate_a_mutually_acceptable_outcome'),
  item('to_meet_you_halfway', 'negotiation_and_complexity', 'productive', 'to meet you halfway', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_returned_purchase', 'negotiation_and_complexity', 'receptive', 'a returned purchase', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_service_booking_gone_wrong', 'negotiation_and_complexity', 'receptive', 'a service booking gone wrong', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_shared_calendar_conflict', 'negotiation_and_complexity', 'receptive', 'a shared calendar conflict', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_stated_constraint', 'negotiation_and_complexity', 'receptive', 'a stated constraint', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_mutually_acceptable_outcome', 'negotiation_and_complexity', 'receptive', 'a mutually acceptable outcome', 'negotiate_a_mutually_acceptable_outcome'),
  item('an_ultimatum', 'negotiation_and_complexity', 'receptive', 'an ultimatum', 'negotiate_a_mutually_acceptable_outcome'),
  item('genuine_ambiguity', 'negotiation_and_complexity', 'receptive', 'genuine ambiguity', 'clarify_an_ambiguous_instruction_precisely'),
  item('a_targeted_question', 'negotiation_and_complexity', 'receptive', 'a targeted question', 'clarify_an_ambiguous_instruction_precisely'),
  item('a_generic_repair_request', 'negotiation_and_complexity', 'receptive', 'a generic repair request', 'clarify_an_ambiguous_instruction_precisely'),
  item('the_original_plan', 'negotiation_and_complexity', 'receptive', 'the original plan', 'propose_and_defend_an_alternative'),
  item('to_meet_the_same_need', 'negotiation_and_complexity', 'receptive', 'to meet the same need', 'propose_and_defend_an_alternative'),
  item('a_justified_alternative', 'negotiation_and_complexity', 'receptive', 'a justified alternative', 'propose_and_defend_an_alternative'),
  item('a_new_fact', 'negotiation_and_complexity', 'receptive', 'a new fact', 'handle_an_unexpected_complication'),
  item('to_respond_coherently', 'negotiation_and_complexity', 'receptive', 'to respond coherently', 'handle_an_unexpected_complication'),
  item('a_mid_conversation_complication', 'negotiation_and_complexity', 'receptive', 'a mid-conversation complication', 'handle_an_unexpected_complication'),
  item('a_service_booking', 'negotiation_and_complexity', 'receptive', 'a service booking', 'negotiate_a_mutually_acceptable_outcome'),
  item('give_and_take_c1', 'negotiation_and_complexity', 'receptive', 'give and take', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_middle_ground_c1', 'negotiation_and_complexity', 'receptive', 'a middle ground', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_competing_constraint', 'negotiation_and_complexity', 'receptive', 'a competing constraint', 'negotiate_a_mutually_acceptable_outcome'),
  item('a_clean_right_answer', 'negotiation_and_complexity', 'receptive', 'no clean right answer', 'handle_an_unexpected_complication'),
  item('a_fallback_option', 'negotiation_and_complexity', 'receptive', 'a fallback option', 'propose_and_defend_an_alternative'),
  item('a_workable_compromise', 'negotiation_and_complexity', 'receptive', 'a workable compromise', 'negotiate_a_mutually_acceptable_outcome'),
  item('to_settle_on_an_outcome', 'negotiation_and_complexity', 'receptive', 'to settle on an outcome', 'negotiate_a_mutually_acceptable_outcome'),

  // --- sustained_interaction (target 10 productive / 17 receptive) ---
  item('anyway_c1', 'sustained_interaction', 'productive', 'anyway', 'sustain_a_conversation_across_topic_shifts'),
  item('speaking_of_which_c1', 'sustained_interaction', 'productive', 'speaking of which', 'sustain_a_conversation_across_topic_shifts'),
  item('before_i_forget', 'sustained_interaction', 'productive', 'before I forget', 'sustain_a_conversation_across_topic_shifts'),
  item('going_back_to_what_you_said_about', 'sustained_interaction', 'productive', 'going back to what you said about', 'refer_back_to_earlier_discourse'),
  item('that_point_you_raised_earlier', 'sustained_interaction', 'productive', 'that point you raised earlier', 'refer_back_to_earlier_discourse'),
  item('as_for_the_other_thing', 'sustained_interaction', 'productive', 'as for the other thing', 'refer_back_to_earlier_discourse'),
  item('sorry_to_get_a_bit_more_formal_but', 'sustained_interaction', 'productive', 'sorry, to get a bit more formal for a second', 'shift_register_within_one_conversation'),
  item('on_a_lighter_note', 'sustained_interaction', 'productive', 'on a lighter note', 'shift_register_within_one_conversation'),
  item('so_to_sum_up_what_weve_agreed', 'sustained_interaction', 'productive', "so, to sum up what we've agreed", 'close_a_complex_interaction_with_a_summary'),
  item('before_we_wrap_up', 'sustained_interaction', 'productive', 'before we wrap up', 'close_a_complex_interaction_with_a_summary'),
  item('a_topic_shift_c1', 'sustained_interaction', 'receptive', 'a topic shift', 'sustain_a_conversation_across_topic_shifts'),
  item('to_track_a_conversation', 'sustained_interaction', 'receptive', 'to track a conversation', 'sustain_a_conversation_across_topic_shifts'),
  item('a_related_topic', 'sustained_interaction', 'receptive', 'a related topic', 'sustain_a_conversation_across_topic_shifts'),
  item('an_accurate_reference', 'sustained_interaction', 'receptive', 'an accurate reference', 'refer_back_to_earlier_discourse'),
  item('a_vague_reference', 'sustained_interaction', 'receptive', 'a vague reference', 'refer_back_to_earlier_discourse'),
  item('to_restate_in_full', 'sustained_interaction', 'receptive', 'to restate in full', 'refer_back_to_earlier_discourse'),
  item('a_register_shift', 'sustained_interaction', 'receptive', 'a register shift', 'shift_register_within_one_conversation'),
  item('to_land_correctly', 'sustained_interaction', 'receptive', 'to land correctly', 'shift_register_within_one_conversation'),
  item('a_mixed_exchange', 'sustained_interaction', 'receptive', 'a mixed personal/practical exchange', 'sustain_a_conversation_across_topic_shifts'),
  item('a_brief_accurate_summary', 'sustained_interaction', 'receptive', 'a brief, accurate summary', 'close_a_complex_interaction_with_a_summary'),
  item('what_was_agreed', 'sustained_interaction', 'receptive', 'what was agreed', 'close_a_complex_interaction_with_a_summary'),
  item('a_catch_up_conversation', 'sustained_interaction', 'receptive', 'a catch-up conversation', 'sustain_a_conversation_across_topic_shifts'),
  item('a_text_mediated_exchange', 'sustained_interaction', 'receptive', 'a text-mediated exchange', 'sustain_a_conversation_across_topic_shifts'),
  item('a_serious_request', 'sustained_interaction', 'receptive', 'a serious request', 'shift_register_within_one_conversation'),
  item('to_track_what_was_said', 'sustained_interaction', 'receptive', 'to track what was said', 'refer_back_to_earlier_discourse'),
  item('to_adjust_mid_conversation', 'sustained_interaction', 'receptive', 'to adjust mid-conversation', 'shift_register_within_one_conversation'),
  item('a_misattributed_reference', 'sustained_interaction', 'receptive', 'a misattributed reference', 'refer_back_to_earlier_discourse'),
]

export const getC1VocabularyForArc = (arcId) => C1_VOCABULARY.filter((v) => v.arc === arcId)

export const C1_VOCABULARY_COUNTS_BY_ARC = C1_VOCABULARY.reduce((acc, v) => {
  acc[v.arc] = acc[v.arc] || { productive: 0, receptive: 0 }
  acc[v.arc][v.kind] += 1
  return acc
}, {})

export const C1_VOCABULARY_TOTALS = C1_VOCABULARY.reduce((acc, v) => {
  acc[v.kind] = (acc[v.kind] || 0) + 1
  return acc
}, {})
