/*
 * ChattoMascot — LinguaChat's official mascot and living logo.
 *
 * The canonical art lives in src/assets/chatto/*.png (1254x1254 masters). This
 * component never draws Chatto: it renders size-bucketed, optimized derivatives
 * (WebP with a PNG fallback) generated by scripts/optimize-chatto.py, loading
 * only the small variant a given screen needs. The mascot is composed into a
 * "scene" — halo, ambient glow, soft sparkles — and moved with wrapper-only
 * transforms so the artwork is never deformed, cropped or recolored.
 *
 * Props (backwards compatible):
 *   mood        'happy' | 'calm' | 'cheering' | 'thinking' | 'supportive' | 'celebrating' | 'welcoming'
 *   size        'small' | 'medium' | 'large' | number (px) — default 'medium' (96)
 *   variant     accent for halo/glow: 'violet' (default) | 'coral' | 'green' | 'blue'
 *   intensity   motion preset: 'static' | 'ambient' | 'enter' | 'guide' | 'celebrate' | 'support'
 *               (defaults derived from mood; `animated={false}` forces 'static')
 *   animated    boolean — legacy switch; false => intensity 'static'
 *   message     optional short caption rendered under the mascot
 *   decorative  boolean — hides the image from assistive tech (aria-hidden)
 *   priority    boolean — eager-load + high fetch priority (use for the portada LCP only)
 *   scene       boolean — draw halo/sparkles for the mood (default true; false = bare figure)
 */

// Eager URL maps for the generated derivatives, keyed by basename (no extension).
const WEBP = keyed(import.meta.glob('../../assets/chatto/gen/*.webp', { eager: true, query: '?url', import: 'default' }), '.webp')
const PNG = keyed(import.meta.glob('../../assets/chatto/gen/*.png', { eager: true, query: '?url', import: 'default' }), '.png')

function keyed(glob, ext) {
  const out = {}
  for (const [path, url] of Object.entries(glob)) {
    out[path.split('/').pop().replace(ext, '')] = url
  }
  return out
}

const SIZES = { small: 64, medium: 96, large: 128 }

// Display -> derivative bucket. Keeps ~2.5-4x density for crisp retina rendering.
function bucketFor(px) {
  if (px <= 48) return 128
  if (px <= 104) return 256
  return 384
}

const MOODS = {
  happy:       { asset: 'official',   halo: false, sparkle: false },
  calm:        { asset: 'calm',       halo: false, sparkle: false },
  cheering:    { asset: 'celebrate',  halo: true,  sparkle: true  },
  thinking:    { asset: 'thinking',   halo: false, sparkle: false },
  supportive:  { asset: 'supportive', halo: true,  sparkle: false },
  celebrating: { asset: 'celebrate',  halo: true,  sparkle: true  },
  welcoming:   { asset: 'welcome',    halo: true,  sparkle: true  },
}

const ACCENT_VAR = {
  violet: 'var(--violet)',
  coral: 'var(--coral)',
  green: 'var(--green)',
  blue: 'var(--blue)',
}

// Motion preset chosen when the caller doesn't pass `intensity`.
function defaultIntensity(mood, animated) {
  if (animated === false) return 'static'
  switch (mood) {
    case 'welcoming': return 'enter'
    case 'celebrating':
    case 'cheering': return 'celebrate'
    case 'supportive': return 'support'
    case 'thinking': return 'guide'
    default: return 'ambient'
  }
}

export function ChattoMascot({
  mood = 'happy',
  size = 'medium',
  variant = 'violet',
  intensity,
  animated = true,
  message = null,
  decorative = false,
  priority = false,
  scene = true,
}) {
  const config = MOODS[mood] || MOODS.happy
  const px = typeof size === 'number' ? size : (SIZES[size] || SIZES.medium)
  const bucket = bucketFor(px)
  const base = `chatto-${config.asset}-${bucket}`
  const webp = WEBP[base]
  const png = PNG[base]
  const accent = ACCENT_VAR[variant] || ACCENT_VAR.violet

  const level = intensity || defaultIntensity(mood, animated)
  const motionClass = level === 'static' ? '' : `chatto-fig-${level}`
  const showHalo = scene && config.halo && level !== 'static'
  const showSparkle = scene && config.sparkle && level !== 'static'

  const alt = decorative ? '' : `Chatto, LinguaChat mascot (${mood})`
  // Small logos live in headers/nav (above the fold) and are only ~12 KB, so load
  // them eagerly to avoid a flash; larger in-card mascots stay lazy.
  const eager = priority || px <= 48

  return (
    <div className="chatto-scene flex flex-col items-center" style={{ userSelect: 'none' }}>
      <div className="chatto-stage" style={{ width: px, height: px }}>
        {showHalo && <span className="chatto-halo-fx" style={{ '--chatto-accent': accent }} aria-hidden="true" />}
        {showSparkle && (
          <span className="chatto-sparkles" aria-hidden="true">
            <i style={{ '--sx': '6%', '--sy': '14%', '--sd': '0s' }} />
            <i style={{ '--sx': '86%', '--sy': '22%', '--sd': '0.5s' }} />
            <i style={{ '--sx': '78%', '--sy': '84%', '--sd': '1s' }} />
          </span>
        )}
        <div
          className={`chatto-figure ${motionClass}`}
          style={{ width: px, height: px, lineHeight: 0 }}
          role={decorative ? undefined : 'img'}
          aria-label={decorative ? undefined : alt}
          aria-hidden={decorative ? 'true' : undefined}
        >
          <picture>
            {webp && <source srcSet={webp} type="image/webp" />}
            <img
              className="chatto-image"
              src={png || webp}
              alt={alt}
              width={px}
              height={px}
              draggable="false"
              loading={eager ? 'eager' : 'lazy'}
              decoding="async"
            />
          </picture>
        </div>
      </div>

      {message && (
        <div
          className="chatto-bubble rounded-2xl px-4 py-2.5 mt-3 text-center"
          style={{ background: 'var(--bg-paper)', border: '1px solid var(--border)', maxWidth: 280 }}
        >
          <p style={{ fontSize: '0.875rem', color: 'var(--ink)', lineHeight: 1.45 }}>{message}</p>
        </div>
      )}
    </div>
  )
}

export default ChattoMascot
